[package]
name = "rustc_macros"
version = "0.0.0"
authors = ["The Rust Project Developers"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
synstructure = "0.12.1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
quote = "1"

[unstable]
proc_macro_diagnostic = "yes"