[package]
name = "ts-core-compiler"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
once_cell = "1.4"
phf = { version = "0.8", features = ["macros"] }
